[2025-05-10 08:37:26] INFO [like_scanner.app] Stopping Like-Scanner API...
[2025-05-10 08:37:26] INFO [like_scanner.app] Closing Savee driver...
[2025-05-10 08:37:26] WARNING [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102860b50>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b6fc7e6a0be7271de72b1c688b41b99f
[2025-05-10 08:37:26] WARNING [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1028724d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b6fc7e6a0be7271de72b1c688b41b99f
[2025-05-10 08:37:26] WARNING [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10287ba10>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b6fc7e6a0be7271de72b1c688b41b99f
[2025-05-10 08:37:26] INFO [like_scanner.app] Savee driver closed.
[2025-05-10 08:37:26] INFO [like_scanner.app] Closing Cosmos driver...
[2025-05-10 08:37:26] ERROR [like_scanner.app] Error while closing Cosmos driver: 'CosmosDriver' object has no attribute 'quit'
Traceback (most recent call last):
  File "/Users/rum/Downloads/IT/Project/Works/savee-cosmos-saves/Code/like_scanner/app.py", line 75, in on_shutdown
    cosmos.quit()
    ^^^^^^^^^^^
AttributeError: 'CosmosDriver' object has no attribute 'quit'
