[2025-05-12 11:01:43] INFO [like_scanner.app] Starting Like-Scanner API...
[2025-05-12 11:01:43] INFO [like_scanner.app] Initializing Savee driver...
[2025-05-12 11:01:43] INFO [like_scanner.infra.drivers.savee_driver] Инициализация Selenium-драйвера для Savee в headless-режиме...
[2025-05-12 11:01:43] INFO [like_scanner.infra.drivers.savee_driver] Создан временный профиль для Chrome: /var/folders/6g/wr22f5d942z1lv830qjt4_gc0000gn/T/savee_profile_23l49x5g
[2025-05-12 11:01:43] INFO [like_scanner.infra.drivers.savee_driver] User-Agent установлен: Mozilla/5.0 (Macintosh, Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
[2025-05-12 11:01:54] INFO [like_scanner.infra.drivers.savee_driver] WebDriver успешно запущен.
[2025-05-12 11:01:54] INFO [like_scanner.infra.drivers.savee_driver] Загружено cookies из /Users/rum/Downloads/IT/Project/Works/savee-cosmos-saves/Code/savee_state.json: 1 шт.
[2025-05-12 11:02:24] INFO [like_scanner.infra.drivers.savee_driver] Cookies успешно добавлены в браузер.
[2025-05-12 11:02:24] INFO [like_scanner.app] Savee driver ready.
[2025-05-12 11:02:24] INFO [like_scanner.app] Initializing Cosmos driver...
[2025-05-12 11:02:25] INFO [cosmos] Chrome WebDriver started (headless=True).
[2025-05-12 11:02:38] INFO [cosmos] Existing Cosmos session restored from cookies.
[2025-05-12 11:02:38] INFO [like_scanner.app] Cosmos driver ready.
[2025-05-12 11:03:28] INFO [like_scanner.app] Stopping Like-Scanner API...
[2025-05-12 11:03:28] INFO [like_scanner.app] Closing Savee driver...
[2025-05-12 11:03:28] WARNING [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10437c910>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/9154f709915e59544a62735710780f4e
[2025-05-12 11:03:28] WARNING [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10438c550>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/9154f709915e59544a62735710780f4e
[2025-05-12 11:03:28] WARNING [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10438c690>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/9154f709915e59544a62735710780f4e
[2025-05-12 11:03:28] INFO [like_scanner.app] Savee driver closed.
[2025-05-12 11:03:28] INFO [like_scanner.app] Closing Cosmos driver...
[2025-05-12 11:03:28] ERROR [like_scanner.app] Error while closing Cosmos driver: 'CosmosDriver' object has no attribute 'quit'
Traceback (most recent call last):
  File "/Users/rum/Downloads/IT/Project/Works/savee-cosmos-saves/Code/like_scanner/app.py", line 75, in on_shutdown
    cosmos.quit()
    ^^^^^^^^^^^
AttributeError: 'CosmosDriver' object has no attribute 'quit'
